// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rezor_MoviePage.Data;

#nullable disable

namespace Rezor_MoviePage.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20240813180240_TransferCost")]
    partial class TransferCost
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rezor_MoviePage.Model.HallCinema", b =>
                {
                    b.Property<int>("NumberHall")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumberHall"));

                    b.Property<int>("CountRows")
                        .HasColumnType("int");

                    b.Property<int>("CountSeats")
                        .HasColumnType("int");

                    b.HasKey("NumberHall");

                    b.ToTable("HallCinema");
                });

            modelBuilder.Entity("Rezor_MoviePage.Model.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("Rezor_MoviePage.Model.Shedule", b =>
                {
                    b.Property<int>("SheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SheduleId"));

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<DateTime>("EndFilm")
                        .HasColumnType("datetime2");

                    b.Property<int>("HallCinemaNumberHall")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartFilm")
                        .HasColumnType("datetime2");

                    b.HasKey("SheduleId");

                    b.HasIndex("HallCinemaNumberHall");

                    b.HasIndex("MovieId");

                    b.ToTable("Shedule");
                });

            modelBuilder.Entity("Rezor_MoviePage.Model.Shedule", b =>
                {
                    b.HasOne("Rezor_MoviePage.Model.HallCinema", "HallCinema")
                        .WithMany()
                        .HasForeignKey("HallCinemaNumberHall")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rezor_MoviePage.Model.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HallCinema");

                    b.Navigation("Movie");
                });
#pragma warning restore 612, 618
        }
    }
}
